import "../globals.css";
import {NextIntlClientProvider} from "next-intl";
import {getMessages} from "next-intl/server";
import {notFound} from "next/navigation";

export const metadata = {
  title: "Gheychi Project",
  description: "Generated by Gheychi Team",
};

export default async function RootLayout({ children, params : {locale} }) {
    let messages;
    let isRtl = false;
    try {
        messages = await getMessages();
        isRtl = locale === 'fa';  // Check if the locale is Persian (fa)
        console.log("hello")
    } catch (error) {
        notFound();
    }
  return (
      <html lang={locale} dir={isRtl ? 'rtl' : 'ltr'}>
      <body>
      <NextIntlClientProvider messages={messages} className={isRtl ? 'rtl' : 'ltr'}>
          {children}
      </NextIntlClientProvider>
      </body>
      </html>
  );
}
